### ISSUE TITLE
Instructions on how to customize the scss variables?

### ISSUE THREAD

**Issue by arnemileswinter** [tylerjlawson/simple-snipcart-shop#2]
I'm not so familiar with scss, and currently investigating how to change the styling. How did you go about this?

**Comment by tylersayshi** [comment]
You can edit the values here: https://github.com/tylerjlawson/simple-snipcart-shop/blob/master/assets/styles/main.scss#L3_L19

If you wanna read up on scss variables, their docs are pretty helpful: https://sass-lang.com/documentation/variables

**Comment by arnemileswinter** [comment]
after i made the change, how would i compile it to css? i tried with node-sass but seeing it is not included in the themes' devDependencies i am not so sure.. what was your workflow to build the css from the scss? maybe im missing something hugo has to offer, fairly new to it.

**Comment by tylersayshi** [comment]
In the `exampleSite` folder you'll see that I have some config files setup to run hugo with postcss to compile the sass to css. If you have setup your site using that folder, you'll just need to run `yarn install` and then `yarn` assuming that you have [yarn](https://classic.yarnpkg.com/lang/en/docs/install/) installed already.

If that does not work, could you link me to your project, so that I can make sure you have everything setup properly.

**Comment by arnemileswinter** [comment]
oh cool didnt know theres a hugo pipe for scss and postcss :)
